// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBFjYjjyzLQVSwCY2dsxyplWLU_j7zmQ',
    appId: '1:437913946832:web:158d315850e5d10e7bacd5',
    messagingSenderId: '437913946832',
    projectId: 'fir-crud-basics-ee0dd',
    authDomain: 'fir-crud-basics-ee0dd.firebaseapp.com',
    storageBucket: 'fir-crud-basics-ee0dd.firebasestorage.app',
    measurementId: 'G-GQSRMD7S0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapABJFEvM1JgWQ2VqDaXunDjqItnH-4Q',
    appId: '1:437913946832:android:7d27d70aceceeb9f7bacd5',
    messagingSenderId: '437913946832',
    projectId: 'fir-crud-basics-ee0dd',
    storageBucket: 'fir-crud-basics-ee0dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAIXtPTh_JJ5364ihvq_dCW1L5zqe0Q0',
    appId: '1:437913946832:ios:4c072097c6f964717bacd5',
    messagingSenderId: '437913946832',
    projectId: 'fir-crud-basics-ee0dd',
    storageBucket: 'fir-crud-basics-ee0dd.firebasestorage.app',
    iosBundleId: 'com.weynard02.crudLocalDatabaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyAIXtPTh_JJ5364ihvq_dCW1L5zqe0Q0',
    appId: '1:437913946832:ios:4c072097c6f964717bacd5',
    messagingSenderId: '437913946832',
    projectId: 'fir-crud-basics-ee0dd',
    storageBucket: 'fir-crud-basics-ee0dd.firebasestorage.app',
    iosBundleId: 'com.weynard02.crudLocalDatabaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsBFjYjjyzLQVSwCY2dsxyplWLU_j7zmQ',
    appId: '1:437913946832:web:607a5293065ac3df7bacd5',
    messagingSenderId: '437913946832',
    projectId: 'fir-crud-basics-ee0dd',
    authDomain: 'fir-crud-basics-ee0dd.firebaseapp.com',
    storageBucket: 'fir-crud-basics-ee0dd.firebasestorage.app',
    measurementId: 'G-6GP4D6FG7W',
  );
}
